import { fileURLToPath } from 'url';
import path, { dirname } from 'path';
import fs from "fs"

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

export function generateScripts() {
  const srcPath = path.resolve(__dirname, "../..", "ckb-labels", "information", "script");
  const dstFilePath = path.resolve(__dirname, "../..", "src", "database", "known-scripts", "scriptList.ts");
  const scriptList = [];
  // read
  const files = fs.readdirSync(srcPath);
  files.forEach(fileName => {
    // if is file pass
    if (fs.statSync(path.resolve(srcPath, fileName)).isFile())
      return
    const folderName = fileName
    const json = fs.readFileSync(path.resolve(srcPath, folderName, "index.json"))
    const jsonObj = JSON.parse(json)
    if(!jsonObj.name) return;
    // console.log(jsonObj)
    scriptList.push(jsonObj);
  })
  fs.writeFileSync(dstFilePath, scriptListFileTemplate(scriptList));
  console.log("generateScripts done")
}

const scriptListFileTemplate = (scriptList) => `/**
* ! This file is generated by the script, do not modify it directly
*/
import { withNetwork } from "@/utils/withNetwork";
import type { KnownScriptDepolyment, KnownScriptInfo } from "./tool";
const knownScriptInfoList: KnownScriptInfo[] = [
${scriptList.map(script => `
  {
    name: "${script.name}",
    description: "${script.description}",
    rfc: "${script.rfc}",
    website: "${script.website}",
    sourceUrl: "${script.sourceUrl}",
    verified: true,
    cellTypeTag: ${script.decoderType ? `"${script.decoderType}"` : "undefined"},
    deployments: withNetwork<KnownScriptDepolyment[]>({
      mainnet: [${script.deployments.mainnet.map(scriptDeploymentToTemplate).join(", ")}],
      testnet: [${script.deployments.testnet.map(scriptDeploymentToTemplate).join(", ")}],
    }, [])
  },`).join("")}
];
export default knownScriptInfoList;
`

const scriptDeploymentToTemplate = (deployment) => `{
        tag: "${deployment.tag}",
        hashType: "${deployment.hashType}",
        dataHash: "${deployment.dataHash}",
        typeHash: "${deployment.typeHash}",
        codeHash: "${deployment.codeHash}",
        deprecated: ${deployment.deprecated},
      }`