
import { fileURLToPath } from 'url';
import path, { dirname } from 'path';
import fs from "fs"

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);


export function generateUDTInfos() {
  genereateSingleNetworkUDTInfos("mainnet", true)
  genereateSingleNetworkUDTInfos("testnet", true)
}


function genereateSingleNetworkUDTInfos(network, famousOnly = false) {  // testnet | mainnet
  const srcPath = path.resolve(__dirname, "../..", "ckb-labels", "information", "udt", network);
  const dstFilePath = path.resolve(__dirname, "../..", "src", "database", "udts", `udts.${network}.ts`);
  const assetFolderPath = path.resolve(__dirname, "../..", "public", "assets", "udt", network);
  const udtList = [];
  // read
  const files = fs.readdirSync(srcPath);
  files.forEach(fileName => {
    // if is file pass
    if (fs.statSync(path.resolve(srcPath, fileName)).isFile())
      return
    const folderName = fileName
    const json = fs.readFileSync(path.resolve(srcPath, folderName, "index.json"))
    const jsonObj = JSON.parse(json)
    
    if (famousOnly && !jsonObj.famous) return;
    if (jsonObj.icon) {
      const iconVal = jsonObj.icon;
      if (!(iconVal.startsWith("http") || iconVal.startsWith("data:"))) {
        const iconFilePath = path.resolve(srcPath, folderName, iconVal);
        const targetIconFolderPath = path.resolve(assetFolderPath, folderName);
        fs.mkdirSync(targetIconFolderPath, { recursive: true });
        fs.copyFileSync(iconFilePath, path.resolve(targetIconFolderPath, iconVal));
        jsonObj.icon = `/assets/udt/${network}/${folderName}/${iconVal}`;
      }
    } else {
      console.log(`UDT ${network} ${jsonObj.name} ${jsonObj.typeHash} no icon`)
      jsonObj.icon = `/assets/udt/default.png`;
    }
    udtList.push(jsonObj);
  })
  fs.writeFileSync(dstFilePath, fileTemplate(network, udtList));
  console.log(`generate ${network} udt infos done`)
}

const fileTemplate = (network, udtList) => `/**
* ! This file is generated by the script, do not modify it directly
*/
import type { UDT } from "./tool";

const ${network}UDTList: UDT[] = [
${udtList.map(udtInfo => `
  {
    name: "${udtInfo.name}",
    icon: "${udtInfo.icon}",
    symbol: "${udtInfo.symbol}",
    decimalPlaces: ${udtInfo.decimal},
    type: {
      codeHash: "${udtInfo.type.codeHash}",
      hashType: "${udtInfo.type.hashType}",
      args: "${udtInfo.type.args}",
    },
    typeHash: "${udtInfo.typeHash}",
    manager: "${udtInfo.manager}",
    tags: [${udtInfo.tags?.map(str => `"${str}"`).join(", ") ?? ""}],
  },`).join("")}
];
export default ${network}UDTList;
`
