/**
* ! This file is generated by the script, do not modify it directly
*/
import type { UDT } from "./tool";

const testnetUDTList: UDT[] = [

  {
    name: "USDI",
    icon: "/assets/udt/testnet/0x07ac97b5ff3df4b49f59a59f4d80d33d22c1263a57467c512c93b9c29b7a0de3/logo.svg",
    symbol: "USDI",
    decimalPlaces: 6,
    type: {
      codeHash: "0xcc9dc33ef234e14bc788c43a4848556a5fb16401a04662fc55db9bb201987037",
      hashType: "type",
      args: "0x71fd1985b2971a9903e4d8ed0d59e6710166985217ca0681437883837b86162f",
    },
    typeHash: "0x07ac97b5ff3df4b49f59a59f4d80d33d22c1263a57467c512c93b9c29b7a0de3",
    manager: "ckt1qzda0cr08m85hc8jlnfp3zer7xulejywt49kt2rr0vthywaa50xwsqvt29ul8eew7c2kycc3r8hcyxlaed8me9gfnzdaf",
    tags: ["rgb++", "layer-2-asset"],
  },
  {
    name: "DRAGON",
    icon: "/assets/udt/testnet/0x2fc6ab428262c64a05e3bba311b9f3196665e9837e207ba683582c379bcbb445/logo.png",
    symbol: "DRAGON",
    decimalPlaces: 8,
    type: {
      codeHash: "0x25c29dc317811a6f6f3985a7a9ebc4838bd388d19d0feeecf0bcd60f6c0975bb",
      hashType: "type",
      args: "0x0de8bf8958dd5fcda833ead2cc2827f3e60b8764b0807fd45c0de805f435a82d",
    },
    typeHash: "0x2fc6ab428262c64a05e3bba311b9f3196665e9837e207ba683582c379bcbb445",
    manager: "ckt1qqkl2w6e9ke6ud59kau84h877qej5cg7mwpu50lv5s6cpxtycwhlyqnhm484dhrc5f6gq5ztaxcjgehkq9v2aelmzrprsfvuwp75sma5n5wgvelk",
    tags: ["rgb++", "layer-2-asset"],
  },
  {
    name: "RUSD",
    icon: "https://raw.githubusercontent.com/stablepp/media-kit/refs/heads/main/stablecoin-RUSD.svg",
    symbol: "RUSD",
    decimalPlaces: 8,
    type: {
      codeHash: "0x1142755a044bf2ee358cba9f2da187ce928c91cd4dc8692ded0337efa677d21a",
      hashType: "type",
      args: "0x878fcc6f1f08d48e87bb1c3b3d5083f23f8a39c5d5c764f253b55b998526439b",
    },
    typeHash: "0x45b32a2bc4285d0a09678eb11960ddc8707bc2779887a09d482e9bfe9a2cdf52",
    manager: "ckt1qrfrwcdnvssswdwpn3s9v8fp87emat306ctjwsm3nmlkjg8qyza2cqgqq9tn3v8fgf8fegvm3n8y7elvpjza4kd7mcd7aek4",
    tags: ["rgb++", "layer-2-asset"],
  },
  {
    name: "ccBTC",
    icon: "/assets/udt/testnet/0x9dfa2259e383423877d1451686d5b2d7d6183b98ee7a977a8e5661bb893226b9/logo.png",
    symbol: "BTC",
    decimalPlaces: 8,
    type: {
      codeHash: "0x98701eaf939113606a8a70013fd2e8f27b8f1e234acdc329f3d71f9e9d3d3233",
      hashType: "type",
      args: "0x5f1c45bd6d5c7f78ac29e9559a62dc3751a516ff2d276460845c82d08378a310",
    },
    typeHash: "0x9dfa2259e383423877d1451686d5b2d7d6183b98ee7a977a8e5661bb893226b9",
    manager: "ckt1qpa0qahsffdrsxtuu97tc2u2wzwaeel3dc7fjjm3vurvtggrggqquqgx2a48py5vhs2ew4g9tsr988r9mvtz8xn8qq388fz6",
    tags: [],
  },
  {
    name: "Stable++",
    icon: "/assets/udt/default.png",
    symbol: "BTCPP",
    decimalPlaces: 8,
    type: {
      codeHash: "0x25c29dc317811a6f6f3985a7a9ebc4838bd388d19d0feeecf0bcd60f6c0975bb",
      hashType: "type",
      args: "0x6d0cc2e3a8059f36dbee473e14b2b05d19a4d69f5bfd2a7abdc71fd32eece546",
    },
    typeHash: "0xcc14aba04f0b03a5df5ef2cc2a163ff34c35863fbd65cd137aede0fb40346f66",
    manager: "ckt1qzda0cr08m85hc8jlnfp3zer7xulejywt49kt2rr0vthywaa50xwsqg47radhdj592lsf77x0x95m328yf40thslxr4tj",
    tags: [],
  },
  {
    name: "iCKB",
    icon: "/assets/udt/testnet/0xd485c2271949c232e3f5d46128336c716f90bcbf3cb278696083689fbbcd407a/logo.png",
    symbol: "iCKB",
    decimalPlaces: 8,
    type: {
      codeHash: "0x50bd8d6680b8b9cf98b73f3c08faf8b2a21914311954118ad6609be6e78a1b95",
      hashType: "data1",
      args: "0xb73b6ab39d79390c6de90a09c96b290c331baf1798ed6f97aed02590929734e800000080",
    },
    typeHash: "0xd485c2271949c232e3f5d46128336c716f90bcbf3cb278696083689fbbcd407a",
    manager: "ckt1qpyald40aewv3tzzykhw4r9cj2932r908nvjl63nw5rg836tzvj55qsjxvwmm",
    tags: ["rgb++"],
  },
];
export default testnetUDTList;
