/**
* ! This file is generated by the script, do not modify it directly
*/
/** */
declare namespace APIExplorer {
  interface UdtPageReq {

    /** 当前页面数据量 {"minimum":1,"example":10} */
    pageSize: number;

    /** 当前页码 {"minimum":1,"example":1} */
    page: number;

    /** 排序 {"example":"typeScriptId.desc | addressesCount.desc | h24CkbTransactionsCount.desc"} */
    sort: string;

  }


  interface PageUdtsListResponse {

    records: Array<UdtsListResponse>;

    total: number;

    size: number;

    current: number;

    /** {"writeOnly":true} */
    orders: Array<OrderItem>;

    optimizeCountSql: PageUdtsListResponse;

    searchCount: PageUdtsListResponse;

    /** {"writeOnly":true} */
    optimizeJoinOfCountSql: boolean;

    /** {"writeOnly":true} */
    maxLimit: number;

    /** {"writeOnly":true} */
    countId: string;

    /** {"deprecated":true} */
    pages: number;

  }


  interface UdtDetailResponse {

    type: string;

    totalAmount: number;

    holdersCount: number;

    typeScriptResponse: TypeScriptResponse;

  }


  interface UdtHolderAllocationsResponse {

    name: string;

    lockType: number;

    holderCount: number;

    hashType: string;

  }


  interface UdtTransactionsPageReq {

    /** 当前页面数据量 {"minimum":1,"example":10} */
    pageSize: number;

    /** 当前页码 {"minimum":1,"example":1} */
    page: number;

    /** 排序方式，默认为time.desc {"example":"time.desc"} */
    sort: string;

    /** 交易哈希 */
    txHash: string;

    /** 地址 */
    addressHash: string;

  }


  interface PageUdtTransactionPageResponse {

    records: Array<UdtTransactionPageResponse>;

    total: number;

    size: number;

    current: number;

    /** {"writeOnly":true} */
    orders: Array<OrderItem>;

    optimizeCountSql: PageUdtTransactionPageResponse;

    searchCount: PageUdtTransactionPageResponse;

    /** {"writeOnly":true} */
    optimizeJoinOfCountSql: boolean;

    /** {"writeOnly":true} */
    maxLimit: number;

    /** {"writeOnly":true} */
    countId: string;

    /** {"deprecated":true} */
    pages: number;

  }


  interface UdtDailyStatisticsResponse {

    ckbTransactionsCount: number;

    holdersCount: number;

    createdAtUnixtimestamp: number;

  }


  interface IndexStatisticResponse {

    type: string;

    epochInfo: EpochInfoResponse;

    tipBlockNumber: number;

    /** {"format":"double"} */
    averageBlockTime: number;

    currentEpochDifficulty: number;

    hashRate: number;

    estimatedEpochTime: number;

    transactionsLast24hrs: number;

    transactionsCountPerMinute: number;

  }


  interface StatisticResponse {

    type: string;

    tipBlockNumber: number;

    averageBlockTime: string;

    currentEpochDifficulty: string;

    hashRate: string;

    minerRanking: {};

    blockchainInfo: BlockchainInfoResponse;

    flushCacheInfo: {};

    addressBalanceRanking: Array<AddressBalanceRanking>;

    maintenanceInfo: {};

    createdAtUnixtimestamp: number;

    transactionFeeRates: TransactionFeeRatesResponse;

  }


  interface CollectionsPageReq {

    /** 当前页面数据量 {"minimum":1,"example":10} */
    pageSize: number;

    /** 当前页码 {"minimum":1,"example":1} */
    page: number;

    /** tags {"example":"tags to filter tokens, availables are \"invalid\", \"suspicious\", \"out-of-length-range\", \"rgb++\", \"layer-1-asset\", \"layer-2-asset\", \"supply-limited\""} */
    tags: string;

    /** 排序 {"example":"block_timestamp.desc"} */
    sort: string;

    /** 类型 {"example":"spore,m_nft"} */
    standard: string;

  }


  interface PageCollectionsResp {

    records: Array<CollectionsResp>;

    total: number;

    size: number;

    current: number;

    /** {"writeOnly":true} */
    orders: Array<OrderItem>;

    optimizeCountSql: PageCollectionsResp;

    searchCount: PageCollectionsResp;

    /** {"writeOnly":true} */
    optimizeJoinOfCountSql: boolean;

    /** {"writeOnly":true} */
    maxLimit: number;

    /** {"writeOnly":true} */
    countId: string;

    /** {"deprecated":true} */
    pages: number;

  }


  interface CollectionsResp {

    id: number;

    /** 名称 */
    name: string;

    /** 描述 */
    description: string;

    /** minted数量 */
    itemsCount: number;

    /** holder数量 */
    holdersCount: number;

    /** 近24小时交易数量 */
    h24CkbTransactionsCount: number;

    /** 标签 */
    tags: Array<string>;

    /** 创建时间 */
    blockTimestamp: number;

    /** 创建人 */
    creator: string;

    /** clusterId */
    clusterId: string;

    /** typeScriptHash */
    typeScriptHash: string;

    /** cell id */
    cellId: number;

    /** icon_url */
    iconUrl: string;

    /** standard */
    standard: string;

  }


  interface NftTransfersPageReq {

    /** 当前页面数据量 {"minimum":1,"example":10} */
    pageSize: number;

    /** 当前页码 {"minimum":1,"example":1} */
    page: number;

    /** 交易哈希 */
    txHash: string;

    /** 地址哈希 */
    addressHash: string;

    /** tokenId */
    tokenId: string;

    /** action {"example":"Mint、Burn、Transfer"} */
    action: string;

  }


  interface PageNftTransfersResp {

    records: Array<NftTransfersResp>;

    total: number;

    size: number;

    current: number;

    /** {"writeOnly":true} */
    orders: Array<OrderItem>;

    optimizeCountSql: PageNftTransfersResp;

    searchCount: PageNftTransfersResp;

    /** {"writeOnly":true} */
    optimizeJoinOfCountSql: boolean;

    /** {"writeOnly":true} */
    maxLimit: number;

    /** {"writeOnly":true} */
    countId: string;

    /** {"deprecated":true} */
    pages: number;

  }


  interface BasePageReq {

    /** 当前页面数据量 {"minimum":1,"example":10} */
    pageSize: number;

    /** 当前页码 {"minimum":1,"example":1} */
    page: number;

  }


  interface PageNftItemDetailResponse {

    records: Array<NftItemDetailResponse>;

    total: number;

    size: number;

    current: number;

    /** {"writeOnly":true} */
    orders: Array<OrderItem>;

    optimizeCountSql: PageNftItemDetailResponse;

    searchCount: PageNftItemDetailResponse;

    /** {"writeOnly":true} */
    optimizeJoinOfCountSql: boolean;

    /** {"writeOnly":true} */
    maxLimit: number;

    /** {"writeOnly":true} */
    countId: string;

    /** {"deprecated":true} */
    pages: number;

  }


  interface NftItemResponse {

    id: number;

    /** 持有者 */
    owner: string;

    /** tokenId */
    tokenId: string;

    /** cell data */
    data: string;

    creator: string;

    standard: string;

    iconUrl: string;

  }


  interface NftHoldersPageReq {

    /** 当前页面数据量 {"minimum":1,"example":10} */
    pageSize: number;

    /** 当前页码 {"minimum":1,"example":1} */
    page: number;

    /** 地址哈希 */
    addressHash: string;

    /** 排序 {"example":"holders_count.desc"} */
    sort: string;

  }


  interface PageNftHolderResp {

    records: Array<NftHolderResp>;

    total: number;

    size: number;

    current: number;

    /** {"writeOnly":true} */
    orders: Array<OrderItem>;

    optimizeCountSql: PageNftHolderResp;

    searchCount: PageNftHolderResp;

    /** {"writeOnly":true} */
    optimizeJoinOfCountSql: boolean;

    /** {"writeOnly":true} */
    maxLimit: number;

    /** {"writeOnly":true} */
    countId: string;

    /** {"deprecated":true} */
    pages: number;

  }


  interface NetInfoResponse {

    type: string;

    version: string;

  }


  interface MonetaryDataResponse {

    nominalApc: Array<string>;

    nominalInflationRate: Array<string>;

    realInflationRate: Array<string>;

  }


  interface MinerDailyStatisticsResponse {

    /** 主键Id */
    id: number;

    type: string;

    createdAtUnixtimestamp: number;

    maxBlockNumber: number;

    minBlockNumber: number;

    totalReward: number;

    totalHashRate: string;

    avgRor: string;

    miners: Array<MinerRewardInfo>;

  }


  interface MinerDailyStatisticsStartEndTimeResponse {

    startTime: number;

    endTime: number;

  }


  interface EpochStatisticsResponse {

    /** 主键Id */
    id: number;

    type: string;

    epochNumber: number;

    difficulty: string;

    uncleRate: number;

    hashRate: string;

    epochTime: number;

    epochLength: number;

    largestBlock: LargestBlockResponse;

    largestTx: LargestTxResponse;

  }


  interface DistributionDataResponse {

    /** 主键Id */
    id: number;

    type: string;

    addressBalanceDistribution: Array<Array<string>>;

    blockTimeDistribution: Array<Array<string>>;

    epochTimeDistribution: Array<Array<string>>;

    averageBlockTime: Array<RollingAvgBlockTime>;

    minerAddressDistribution: {};

  }


  interface DaoDepositorResponse {

    type: string;

    id: number;

    addressHash: string;

    daoDeposit: number;

  }


  interface DailyStatisticResponse {

    /** 主键Id */
    id: number;

    type: string;

    transactionsCount: number;

    addressesCount: number;

    totalDaoDeposit: string;

    createdAtUnixtimestamp: number;

    miningReward: string;

    depositCompensation: string;

    treasuryAmount: string;

    liveCellsCount: string;

    deadCellsCount: string;

    avgHashRate: string;

    avgDifficulty: string;

    uncleRate: string;

    totalDepositorsCount: string;

    totalTxFee: number;

    dailyDaoDeposit: number;

    dailyDaoDepositorsCount: number;

    circulationRatio: number;

    circulatingSupply: number;

    burnt: number;

    lockedCapacity: number;

    liquidity: number;

    /** {"additionalProperties":{"type":"string"}} */
    ckbHodlWave: {};

    holderCount: number;

    knowledgeSize: number;

    /** {"additionalProperties":{"type":"string"}} */
    activityAddressContractDistribution: {};

  }


  interface DaoContractResponse {

    type: string;

    totalDeposit: string;

    depositorsCount: string;

    depositChanges: string;

    unclaimedCompensationChanges: string;

    claimedCompensationChanges: string;

    depositorChanges: string;

    unclaimedCompensation: string;

    claimedCompensation: string;

    averageDepositTime: string;

    miningReward: string;

    depositCompensation: string;

    treasuryAmount: string;

    estimatedApc: string;

  }


  interface ContractTransactionsPageReq {

    /** 当前页面数据量 {"minimum":1,"example":10} */
    pageSize: number;

    /** 当前页码 {"minimum":1,"example":1} */
    page: number;

    /** 交易哈希 */
    txHash: string;

    /** 地址哈希 */
    addressHash: string;

  }


  interface PageContractTransactionPageResponse {

    records: Array<ContractTransactionPageResponse>;

    total: number;

    size: number;

    current: number;

    /** {"writeOnly":true} */
    orders: Array<OrderItem>;

    optimizeCountSql: PageContractTransactionPageResponse;

    searchCount: PageContractTransactionPageResponse;

    /** {"writeOnly":true} */
    optimizeJoinOfCountSql: boolean;

    /** {"writeOnly":true} */
    maxLimit: number;

    /** {"writeOnly":true} */
    countId: string;

    /** {"deprecated":true} */
    pages: number;

  }


  interface TransactionPageReq {

    /** 当前页面数据量 {"minimum":1,"example":10} */
    pageSize: number;

    /** 当前页码 {"minimum":1,"example":1} */
    page: number;

    /** 排序字段 */
    sort: string;

  }


  interface PageTransactionPageResponse {

    records: Array<TransactionPageResponse>;

    total: number;

    size: number;

    current: number;

    /** {"writeOnly":true} */
    orders: Array<OrderItem>;

    optimizeCountSql: PageTransactionPageResponse;

    searchCount: PageTransactionPageResponse;

    /** {"writeOnly":true} */
    optimizeJoinOfCountSql: boolean;

    /** {"writeOnly":true} */
    maxLimit: number;

    /** {"writeOnly":true} */
    countId: string;

    /** {"deprecated":true} */
    pages: number;

  }


  interface TransactionResponse {

    /** 主键Id */
    id: number;

    type: string;

    isCellbase: boolean;

    txStatus: string;

    witnesses: Array<string>;

    cellDeps: Array<CellDependencyResponse>;

    headerDeps: Array<string>;

    detailedMessage: string;

    transactionHash: string;

    transactionFee: number;

    blockNumber: number;

    version: string;

    blockTimestamp: number;

    bytes: number;

    largestTxInEpoch: number;

    largestTx: number;

    cycles: number;

    maxCyclesInEpoch: number;

    maxCycles: number;

    isRgbTransaction: boolean;

    isBtcTimeLock: boolean;

    rgbTxid: string;

    rgbTransferStep: string;

  }


  interface PageCellOutputResponse {

    records: Array<CellOutputResponse>;

    total: number;

    size: number;

    current: number;

    /** {"writeOnly":true} */
    orders: Array<OrderItem>;

    optimizeCountSql: PageCellOutputResponse;

    searchCount: PageCellOutputResponse;

    /** {"writeOnly":true} */
    optimizeJoinOfCountSql: boolean;

    /** {"writeOnly":true} */
    maxLimit: number;

    /** {"writeOnly":true} */
    countId: string;

    /** {"deprecated":true} */
    pages: number;

  }


  interface PageCellInputResponse {

    records: Array<CellInputResponse>;

    total: number;

    size: number;

    current: number;

    /** {"writeOnly":true} */
    orders: Array<OrderItem>;

    optimizeCountSql: PageCellInputResponse;

    searchCount: PageCellInputResponse;

    /** {"writeOnly":true} */
    optimizeJoinOfCountSql: boolean;

    /** {"writeOnly":true} */
    maxLimit: number;

    /** {"writeOnly":true} */
    countId: string;

    /** {"deprecated":true} */
    pages: number;

  }


  interface TransactionPageResponse {

    /** 主键Id */
    id: number;

    type: string;

    transactionHash: string;

    blockNumber: number;

    blockTimestamp: number;

    capacityInvolved: number;

    liveCellChanges: number;

  }


  interface PagePendingTransactionPageResponse {

    records: Array<PendingTransactionPageResponse>;

    total: number;

    size: number;

    current: number;

    /** {"writeOnly":true} */
    orders: Array<OrderItem>;

    optimizeCountSql: PagePendingTransactionPageResponse;

    searchCount: PagePendingTransactionPageResponse;

    /** {"writeOnly":true} */
    optimizeJoinOfCountSql: boolean;

    /** {"writeOnly":true} */
    maxLimit: number;

    /** {"writeOnly":true} */
    countId: string;

    /** {"deprecated":true} */
    pages: number;

  }


  interface CellOutputDataResponse {

    type: string;

    data: string;

  }


  interface CellInfoResponse {

    /** 主键Id */
    id: number;

    capacity: number;

    occupiedCapacity: number;

    status: number;

    cellIndex: number;

    generatedTxHash: string;

    consumedTxHash: string;

    lockScript: LockScriptResponse;

    address: string;

    typeScript: TypeScriptResponse;

    data: string;

    dataSize: number;

    cellType: number;

    extraInfo: ExtraInfoResponse;

  }


  interface BlockPageReq {

    /** 当前页面数据量 {"minimum":1,"example":10} */
    pageSize: number;

    /** 当前页码 {"minimum":1,"example":1} */
    page: number;

    /** 排序字段 */
    sort: string;

  }


  interface PageBlockListResponse {

    records: Array<BlockListResponse>;

    total: number;

    size: number;

    current: number;

    /** {"writeOnly":true} */
    orders: Array<OrderItem>;

    optimizeCountSql: PageBlockListResponse;

    searchCount: PageBlockListResponse;

    /** {"writeOnly":true} */
    optimizeJoinOfCountSql: boolean;

    /** {"writeOnly":true} */
    maxLimit: number;

    /** {"writeOnly":true} */
    countId: string;

    /** {"deprecated":true} */
    pages: number;

  }


  interface BlockResponse {

    /** 主键Id */
    id: number;

    type: string;

    blockHash: string;

    uncleBlockHashes: Array<string>;

    minerHash: string;

    transactionsRoot: string;

    rewardStatus: string;

    receivedTxFeeStatus: string;

    minerMessage: string;

    number: number;

    startNumber: number;

    length: number;

    version: string;

    proposalsCount: number;

    unclesCount: number;

    timestamp: number;

    reward: number;

    cellConsumed: number;

    totalTransactionFee: number;

    transactionsCount: number;

    totalCellCapacity: number;

    receivedTxFee: number;

    epoch: number;

    blockIndexInEpoch: number;

    nonce: string;

    difficulty: number;

    minerReward: number;

    size: number;

    largestBlockInEpoch: number;

    largestBlock: number;

    cycles: number;

    maxCyclesInEpoch: number;

    maxCycles: number;

  }


  interface BlockListResponse {

    /** 主键Id */
    id: number;

    type: string;

    minerHash: string;

    number: number;

    timestamp: number;

    reward: number;

    transactionsCount: number;

    liveCellChanges: number;

  }


  interface Last7DaysCkbNodeVersionResponse {

    version: string;

    count: number;

  }


  interface BlockTransactionPageReq {

    /** 当前页面数据量 {"minimum":1,"example":10} */
    pageSize: number;

    /** 当前页码 {"minimum":1,"example":1} */
    page: number;

    /** 交易哈希 */
    txHash: string;

    /** 地址 */
    addressHash: string;

  }


  interface PageBlockTransactionPageResponse {

    records: Array<BlockTransactionPageResponse>;

    total: number;

    size: number;

    current: number;

    /** {"writeOnly":true} */
    orders: Array<OrderItem>;

    optimizeCountSql: PageBlockTransactionPageResponse;

    searchCount: PageBlockTransactionPageResponse;

    /** {"writeOnly":true} */
    optimizeJoinOfCountSql: boolean;

    /** {"writeOnly":true} */
    maxLimit: number;

    /** {"writeOnly":true} */
    countId: string;

    /** {"deprecated":true} */
    pages: number;

  }


  interface AddressResponse {

    /** 主键Id */
    id: number;

    type: string;

    addressHash: string;

    balance: number;

    daoDeposit: number;

    interest: number;

    liveCellsCount: number;

    lockScript: LockScriptResponse;

    phase1UnClaimedCompensation: number;

    depositUnmadeCompensation: number;

    balanceOccupied: number;

    bitcoinAddressHash: string;

  }


  interface AccountUdtBalanceResponse {

    fullName: string;

    symbol: string;

    decimal: number;

    amount: number;

    udtIconFile: string;

    udtType: number;

    udtTypeScript: ScriptResponse;

    typeScriptId: number;

    typeScriptHash: string;

    totalAmount: number;

    expectedSupply: string;

    mint_status: string;

    collection: Array<CollectionTypeHashResponse>;

  }


  interface AccountNftResponse {

    /** nft collection 名称 */
    collectionName: string;

    /** nft collection typeHash */
    collectionTypeHash: string;

    /** tokenId */
    tokenId: string;

    /** nft图片信息 */
    nftIconFile: string;

    /** cell id */
    cellId: number;

    standard: string;

    iconUrl: string;

  }


  interface AddressTransactionsPageReq {

    /** 当前页面数据量 {"minimum":1,"example":10} */
    pageSize: number;

    /** 当前页码 {"minimum":1,"example":1} */
    page: number;

    /** 排序方式，默认为time.desc {"example":"time.desc"} */
    sort: string;

    /** 开始时间 {"format":"date"} */
    startTime: string;

    /** 结束时间 {"format":"date"} */
    endTime: string;

  }


  interface PageAddressTransactionPageResponse {

    records: Array<AddressTransactionPageResponse>;

    total: number;

    size: number;

    current: number;

    /** {"writeOnly":true} */
    orders: Array<OrderItem>;

    optimizeCountSql: PageAddressTransactionPageResponse;

    searchCount: PageAddressTransactionPageResponse;

    /** {"writeOnly":true} */
    optimizeJoinOfCountSql: boolean;

    /** {"writeOnly":true} */
    maxLimit: number;

    /** {"writeOnly":true} */
    countId: string;

    /** {"deprecated":true} */
    pages: number;

  }


  interface AddressLiveCellsPageReq {

    /** 当前页面数据量 {"minimum":1,"example":10} */
    pageSize: number;

    /** 当前页码 {"minimum":1,"example":1} */
    page: number;

    typeHash: string;

  }


  interface PageLiveCellsResponse {

    records: Array<LiveCellsResponse>;

    total: number;

    size: number;

    current: number;

    /** {"writeOnly":true} */
    orders: Array<OrderItem>;

    optimizeCountSql: PageLiveCellsResponse;

    searchCount: PageLiveCellsResponse;

    /** {"writeOnly":true} */
    optimizeJoinOfCountSql: boolean;

    /** {"writeOnly":true} */
    maxLimit: number;

    /** {"writeOnly":true} */
    countId: string;

    /** {"deprecated":true} */
    pages: number;

  }


  interface UdtsListResponse {

    type: string;

    typeScriptHash: string;

    h24CkbTransactionsCount: number;

    addressesCount: number;

  }


  interface OrderItem {

    column: string;

    asc: boolean;

  }


  interface TypeScriptResponse {

    type: string;

    args: string;

    codeHash: string;

    hashType: string;

    verifiedScriptName: string;

    scriptHash: string;

  }


  interface UdtTransactionPageResponse {

    /** 主键Id */
    id: number;

    type: string;

    isCellbase: boolean;

    transactionHash: string;

    blockNumber: number;

    blockTimestamp: number;

    displayInputsCount: number;

    displayOutputsCount: number;

    displayInputs: Array<CellInputResponse>;

    displayOutputs: Array<CellOutputResponse>;

  }


  interface EpochInfoResponse {

    epochNumber: number;

    epochLength: number;

    index: number;

  }


  interface BlockchainInfoResponse {

    isInitialBlockDownload: boolean;

    epoch: number;

    difficulty: number;

    medianTime: number;

    chain: string;

    alerts: Array<AlertMessage>;

    initialBlockDownload: boolean;

  }


  interface AddressBalanceRanking {

    address: string;

    balance: string;

    ranking: number;

  }


  interface TransactionFeeRatesResponse {

    transactionFeeRates: Array<TransactionFeeRates>;

    lastNDaysTransactionFeeRates: Array<LastNDaysTransactionFeeRates>;

  }


  interface NftTransfersResp {

    id: number;

    /** tokenId */
    tokenId: string;

    /** from地址hash */
    from: string;

    /** to地址hash */
    to: string;

    /** action {"example":"Mint、Burn、Transfer"} */
    action: string;

    /** 交易hash */
    txHash: string;

    /** 交易时间 */
    blockTimestamp: number;

    /** cell data */
    data: string;

    standard: string;

    iconUrl: string;

  }


  interface NftItemDetailResponse {

    id: number;

    /** 持有者 */
    owner: string;

    /** tokenId */
    tokenId: string;

    /** cell data */
    data: string;

    /** collection名称 */
    collectionName: string;

    /** collection id */
    collectionId: number;

    creator: string;

    standard: string;

    iconUrl: string;

  }


  interface NftHolderResp {

    /** 地址hash */
    addressHash: string;

    /** 持有者数量 */
    holdersCount: number;

  }


  interface MinerRewardInfo {

    miner: string;

    count: number;

    userReward: number;

    percent: number;

    userHashRate: number;

  }


  interface LargestBlockResponse {

    number: number;

    size: number;

  }


  interface LargestTxResponse {

    txHash: string;

    bytes: number;

  }


  interface RollingAvgBlockTime {

    timestamp: number;

    avgBlockTimeDaily: number;

    avgBlockTimeWeekly: number;

  }


  interface ContractTransactionPageResponse {

    /** 主键Id */
    id: number;

    type: string;

    isCellbase: boolean;

    transactionHash: string;

    blockNumber: number;

    blockTimestamp: number;

    displayInputsCount: number;

    displayOutputsCount: number;

    displayInputs: Array<CellInputResponse>;

    displayOutputs: Array<CellOutputResponse>;

  }


  interface CellDependencyResponse {

    outPoint: OutPoint;

    depType: string;

  }


  interface CellOutputResponse {

    /** 主键Id */
    id: number;

    capacity: number;

    occupiedCapacity: number;

    addressHash: string;

    targetBlockNumber: number;

    status: number;

    consumedTxHash: string;

    cellType: number;

    generatedTxHash: string;

    cellIndex: number;

    typeScript: ScriptResponse;

    data: string;

  }


  interface CellInputResponse {

    /** 主键Id */
    id: number;

    fromCellbase: boolean;

    capacity: number;

    occupiedCapacity: number;

    addressHash: string;

    targetBlockNumber: number;

    generatedTxHash: string;

    cellIndex: number;

    cellType: number;

    since: SinceResponse;

    typeScript: ScriptResponse;

    data: string;

    nervosDaoInfo: NervosDaoInfoResponse;

  }


  interface PendingTransactionPageResponse {

    type: string;

    transactionHash: string;

    bytes: number;

    createdAt: number;

    createTimestamp: number;

  }


  interface LockScriptResponse {

    type: string;

    args: string;

    codeHash: string;

    hashType: string;

    verifiedScriptName: string;

    tags: Array<string>;

  }


  interface ExtraInfoResponse {

    type: string;

    capacity: number;

    symbol: string;

    amount: number;

    decimal: number;

    typeHash: string;

    published: boolean;

    codeHash: string;

    issuerName: string;

    className: string;

    total: string;

    tokenId: string;

    collection: Array<string>;

    clusterName: string;

    name: string;

  }


  interface BlockTransactionPageResponse {

    /** 主键Id */
    id: number;

    type: string;

    isCellbase: boolean;

    transactionHash: string;

    blockNumber: number;

    blockTimestamp: number;

    displayInputsCount: number;

    displayOutputsCount: number;

    displayInputs: Array<CellInputResponse>;

    displayOutputs: Array<CellOutputResponse>;

    isRgbTransaction: boolean;

    isBtcTimeLock: boolean;

    rgbTxid: string;

    rgbTransferStep: string;

  }


  interface ScriptResponse {

    args: string;

    codeHash: string;

    hashType: string;

  }


  interface CollectionTypeHashResponse {

    typeHash: {};

  }


  interface AddressTransactionPageResponse {

    /** 主键Id */
    id: number;

    type: string;

    isCellbase: boolean;

    transactionHash: string;

    blockNumber: number;

    blockTimestamp: number;

    displayInputsCount: number;

    displayOutputsCount: number;

    displayInputs: Array<CellInputResponse>;

    displayOutputs: Array<CellOutputResponse>;

  }


  interface LiveCellsResponse {

    /** 主键Id */
    id: number;

    cellType: number;

    typeScriptId: number;

    txHash: string;

    cellIndex: number;

    typeHash: string;

    data: string;

    tags: Array<string>;

    blockNumber: number;

    capacity: number;

    occupiedCapacity: number;

    blockTimestamp: number;

    extraInfo: ExtraInfoResponse;

  }


  interface AlertMessage {

    id: number;

    priority: number;

    noticeUntil: number;

    message: string;

  }


  interface TransactionFeeRates {

    id: string;

    feeRate: string;

    timestamp: string;

    confirmationTime: string;

  }


  interface LastNDaysTransactionFeeRates {

    date: string;

    feeRate: string;

  }


  interface OutPoint {

    txHash: string;

    index: number;

  }


  interface SinceResponse {

    raw: string;

    medianTimestamp: number;

  }


  interface NervosDaoInfoResponse {

    compensationStartedBlockNumber: number;

    compensationStartedTimestamp: number;

    compensationEndedBlockNumber: number;

    compensationEndedTimestamp: number;

    interest: number;

    lockedUntilBlockNumber: number;

    lockedUntilBlockTimestamp: number;

  }



}