/**
* ! This file is generated by the script, do not modify it directly
*/
import defineAPI from "./defineAPI";

const apiMap = {
  /** UDT列表 */
  "GET /udts": defineAPI<APIExplorer.UdtPageReq, APIExplorer.PageUdtsListResponse>("/udts", "GET"),
  /** UDT详情 */
  "GET /udts/{typeScriptHash}": defineAPI<{ typeScriptHash: string }, APIExplorer.UdtDetailResponse>("/udts/{typeScriptHash}", "GET", {divider: {"path":["typeScriptHash"]}}),
  /** Udt holder allocation */
  "GET /udts/{typeScriptHash}/holder_allocation": defineAPI<{ typeScriptHash: string }, Array<APIExplorer.UdtHolderAllocationsResponse>>("/udts/{typeScriptHash}/holder_allocation", "GET", {divider: {"path":["typeScriptHash"]}}),
  /** UDT交易列表 */
  "GET /udt_transactions/{typeScriptHash}": defineAPI<APIExplorer.UdtTransactionsPageReq & { typeScriptHash: string }, APIExplorer.PageUdtTransactionPageResponse>("/udt_transactions/{typeScriptHash}", "GET", {divider: {"path":["typeScriptHash"]}}),
  /**  */
  "GET /udt_hourly_statistics": defineAPI<{ limit?: number }, Array<APIExplorer.UdtDailyStatisticsResponse>>("/udt_hourly_statistics", "GET"),
  /**  */
  "GET /suggest_queries": defineAPI<{ q: string,filterBy?: number }, {}>("/suggest_queries", "GET"),
  /** 获取统计信息索引 */
  "GET /statistics": defineAPI<null, APIExplorer.IndexStatisticResponse>("/statistics", "GET"),
  /** 获取指定统计信息 */
  "GET /statistics/{fieldName}": defineAPI<{ fieldName: string }, APIExplorer.StatisticResponse>("/statistics/{fieldName}", "GET", {divider: {"path":["fieldName"]}}),
  /** 获取store cell */
  "GET /nft/storeCell/{tokenId}": defineAPI<{ tokenId: string }, number>("/nft/storeCell/{tokenId}", "GET", {divider: {"path":["tokenId"]}}),
  /** 获取collections列表 */
  "GET /nft/collections": defineAPI<APIExplorer.CollectionsPageReq, APIExplorer.PageCollectionsResp>("/nft/collections", "GET"),
  /** 获取collections详情 */
  "GET /nft/collections/{typeScriptHash}": defineAPI<{ typeScriptHash: string }, APIExplorer.CollectionsResp>("/nft/collections/{typeScriptHash}", "GET", {divider: {"path":["typeScriptHash"]}}),
  /** 获取transfers列表 */
  "GET /nft/collections/{typeScriptHash}/transfers": defineAPI<APIExplorer.NftTransfersPageReq & { typeScriptHash: string }, APIExplorer.PageNftTransfersResp>("/nft/collections/{typeScriptHash}/transfers", "GET", {divider: {"path":["typeScriptHash"]}}),
  /** 获取items列表 */
  "GET /nft/collections/{typeScriptHash}/items": defineAPI<APIExplorer.BasePageReq & { typeScriptHash: string }, APIExplorer.PageNftItemDetailResponse>("/nft/collections/{typeScriptHash}/items", "GET", {divider: {"path":["typeScriptHash"]}}),
  /** 获取items详情 */
  "GET /nft/collections/{typeScriptHash}/items/{tokenId}": defineAPI<{ typeScriptHash: string,tokenId: string }, APIExplorer.NftItemResponse>("/nft/collections/{typeScriptHash}/items/{tokenId}", "GET", {divider: {"path":["typeScriptHash","tokenId"]}}),
  /** 获取holders列表 */
  "GET /nft/collections/{typeScriptHash}/holders": defineAPI<APIExplorer.NftHoldersPageReq & { typeScriptHash: string }, APIExplorer.PageNftHolderResp>("/nft/collections/{typeScriptHash}/holders", "GET", {divider: {"path":["typeScriptHash"]}}),
  /** 获取本地节点信息版本号 */
  "GET /nets/version": defineAPI<null, APIExplorer.NetInfoResponse>("/nets/version", "GET"),
  /**  */
  "GET /monetary_data/{indicator}": defineAPI<{ indicator: string }, APIExplorer.MonetaryDataResponse>("/monetary_data/{indicator}", "GET", {divider: {"path":["indicator"]}}),
  /** 获取指定日期的统计数据 */
  "GET /miner_daily_statistics/{date}": defineAPI<{ date: string }, APIExplorer.MinerDailyStatisticsResponse>("/miner_daily_statistics/{date}", "GET", {divider: {"path":["date"]}}),
  /** 获取已统计的开始结束时间 */
  "GET /miner_daily_statistics/start_end_time": defineAPI<null, APIExplorer.MinerDailyStatisticsStartEndTimeResponse>("/miner_daily_statistics/start_end_time", "GET"),
  /** 获取矿工统计信息索引 */
  "GET /miner_daily_statistics/avg_ror": defineAPI<null, Array<APIExplorer.MinerDailyStatisticsResponse>>("/miner_daily_statistics/avg_ror", "GET"),
  /**  */
  "GET /epoch_statistics/{indicator}": defineAPI<{ indicator: string,limit?: number }, Array<APIExplorer.EpochStatisticsResponse>>("/epoch_statistics/{indicator}", "GET", {divider: {"path":["indicator"]}}),
  /** 获取分布数据 */
  "GET /distribution_data/{indicator}": defineAPI<{ indicator: string,limit?: number }, APIExplorer.DistributionDataResponse>("/distribution_data/{indicator}", "GET", {divider: {"path":["indicator"]}}),
  /**  */
  "GET /dao_depositors": defineAPI<null, Array<APIExplorer.DaoDepositorResponse>>("/dao_depositors", "GET"),
  /**  */
  "GET /daily_statistics/{indicator}": defineAPI<{ indicator: string,limit?: number }, Array<APIExplorer.DailyStatisticResponse>>("/daily_statistics/{indicator}", "GET", {divider: {"path":["indicator"]}}),
  /**  */
  "GET /contracts/nervos_dao": defineAPI<null, APIExplorer.DaoContractResponse>("/contracts/nervos_dao", "GET"),
  /** 获取Dao相关的交易列表 */
  "GET /contract_transactions/nervos_dao": defineAPI<APIExplorer.ContractTransactionsPageReq, APIExplorer.PageContractTransactionPageResponse>("/contract_transactions/nervos_dao", "GET"),
  /** 获取交易列表 */
  "GET /ckb_transactions": defineAPI<APIExplorer.TransactionPageReq, APIExplorer.PageTransactionPageResponse>("/ckb_transactions", "GET"),
  /** 获取交易详情 */
  "GET /ckb_transactions/{txHash}": defineAPI<{ txHash: string }, APIExplorer.TransactionResponse>("/ckb_transactions/{txHash}", "GET", {divider: {"path":["txHash"]}}),
  /** 获取交易输出单元格列表 */
  "GET /ckb_transactions/{txHash}/display_outputs": defineAPI<APIExplorer.BasePageReq & { txHash: string }, APIExplorer.PageCellOutputResponse>("/ckb_transactions/{txHash}/display_outputs", "GET", {divider: {"path":["txHash"]}}),
  /** 获取交易输入单元格列表 */
  "GET /ckb_transactions/{txHash}/display_inputs": defineAPI<APIExplorer.BasePageReq & { txHash: string }, APIExplorer.PageCellInputResponse>("/ckb_transactions/{txHash}/display_inputs", "GET", {divider: {"path":["txHash"]}}),
  /** 获取首页交易列表 */
  "GET /ckb_transactions/homePage": defineAPI<{ pageSize: number }, Array<APIExplorer.TransactionPageResponse>>("/ckb_transactions/homePage", "GET"),
  /** 获取Pending交易列表 */
  "GET /ckb_pending_transactions": defineAPI<APIExplorer.BasePageReq, APIExplorer.PagePendingTransactionPageResponse>("/ckb_pending_transactions", "GET"),
  /** 获取CellOutput的数据 */
  "GET /cell_output_data/{id}": defineAPI<{ id: string }, APIExplorer.CellOutputDataResponse>("/cell_output_data/{id}", "GET", {divider: {"path":["id"]}}),
  /** 获取CellInfo的数据 */
  "GET /cell_output/{id}": defineAPI<{ id: string }, APIExplorer.CellInfoResponse>("/cell_output/{id}", "GET", {divider: {"path":["id"]}}),
  /** 获取块列表 */
  "GET /blocks": defineAPI<APIExplorer.BlockPageReq, APIExplorer.PageBlockListResponse>("/blocks", "GET"),
  /** 获取块详情 */
  "GET /blocks/{id}": defineAPI<{ id: string }, APIExplorer.BlockResponse>("/blocks/{id}", "GET", {divider: {"path":["id"]}}),
  /** 获取首页块列表 */
  "GET /blocks/homePage": defineAPI<{ pageSize: number }, Array<APIExplorer.BlockListResponse>>("/blocks/homePage", "GET"),
  /** 获取CKB矿工的节点版本 */
  "GET /blocks/ckb_node_versions": defineAPI<null, Array<APIExplorer.Last7DaysCkbNodeVersionResponse>>("/blocks/ckb_node_versions", "GET"),
  /** 获取区块内的交易列表 */
  "GET /block_transactions/{id}": defineAPI<APIExplorer.BlockTransactionPageReq & { id: string }, APIExplorer.PageBlockTransactionPageResponse>("/block_transactions/{id}", "GET", {divider: {"path":["id"]}}),
  /** 获取地址详情 */
  "GET /addresses/{address}": defineAPI<{ address: string }, APIExplorer.AddressResponse>("/addresses/{address}", "GET", {divider: {"path":["address"]}}),
  /** 获取地址UDT的余额 */
  "GET /addresses/{address}/udts": defineAPI<{ address: string }, Array<APIExplorer.AccountUdtBalanceResponse>>("/addresses/{address}/udts", "GET", {divider: {"path":["address"]}}),
  /** 获取地址NFT信息 */
  "GET /addresses/{address}/nfts": defineAPI<{ address: string }, Array<APIExplorer.AccountNftResponse>>("/addresses/{address}/nfts", "GET", {divider: {"path":["address"]}}),
  /** 获取地址的交易列表 */
  "GET /address_transactions/{address}": defineAPI<APIExplorer.AddressTransactionsPageReq & { address: string }, APIExplorer.PageAddressTransactionPageResponse>("/address_transactions/{address}", "GET", {divider: {"path":["address"]}}),
  /** 获取地址的liveCell列表 */
  "GET /address_live_cells/{address}": defineAPI<APIExplorer.AddressLiveCellsPageReq & { address: string }, APIExplorer.PageLiveCellsResponse>("/address_live_cells/{address}", "GET", {divider: {"path":["address"]}})
}
export default apiMap;
export type APIMap = typeof apiMap;
export type APIPaths = keyof APIMap;
